// Generated by CoffeeScript 2.7.0
(function() {
  // Initialize stats from localStorage
  var downloadOSTEP, handleFormStatus, initializeStats, showNotification;

  initializeStats = function() {
    var activeUsers, downloads, downloadsEl, usersEl;
    downloads = localStorage.getItem('ostpe_downloads') || '0';
    activeUsers = localStorage.getItem('ostpe_active_users') || '0';
    downloadsEl = document.getElementById('total-downloads');
    usersEl = document.getElementById('active-users');
    if (downloadsEl) {
      downloadsEl.textContent = downloads;
    }
    if (usersEl) {
      return usersEl.textContent = activeUsers;
    }
  };

  // Handle download button clicks
  downloadOSTEP = function(event, edition) {
    var currentDownloads, currentUsers, downloadsEl, sessionKey, usersEl;
    event.preventDefault();
    currentDownloads = parseInt(localStorage.getItem('ostpe_downloads')) || 0;
    currentUsers = parseInt(localStorage.getItem('ostpe_active_users')) || 0;
    // Increment downloads
    currentDownloads++;
    // Increment active users (once per session, check with a flag)
    sessionKey = 'ostpe_user_counted_' + new Date().toDateString();
    if (!sessionStorage.getItem(sessionKey)) {
      currentUsers++;
      sessionStorage.setItem(sessionKey, 'true');
    }
    // Save to localStorage
    localStorage.setItem('ostpe_downloads', currentDownloads);
    localStorage.setItem('ostpe_active_users', currentUsers);
    // Update display
    downloadsEl = document.getElementById('total-downloads');
    usersEl = document.getElementById('active-users');
    if (downloadsEl) {
      downloadsEl.textContent = currentDownloads;
      // Add animation
      downloadsEl.style.transform = 'scale(1.2)';
      setTimeout(function() {
        return downloadsEl.style.transform = 'scale(1)';
      }, 300);
    }
    if (usersEl && currentUsers > 0) {
      usersEl.textContent = currentUsers;
      usersEl.style.transform = 'scale(1.2)';
      setTimeout(function() {
        return usersEl.style.transform = 'scale(1)';
      }, 300);
    }
    // Show success message
    showNotification(`${edition.charAt(0).toUpperCase() + edition.slice(1)} Edition download started!`);
    document.getElementById("plswork").addEventListener("click", function() {
      var link;
      link = document.createElement("a");
      link.href = "test/os";
      link.download = "os";
      document.body.appendChild(link);
      link.click();
      return link.remove();
    });
    // Simulate download after a short delay
    return setTimeout(function() {
      return console.log(`Download for ${edition} edition initiated`);
    // In a real scenario, you would trigger an actual download here
    }, 500);
  };

  // Show notification
  showNotification = function(message) {
    var notification;
    notification = document.createElement('div');
    notification.className = 'notification';
    notification.textContent = message;
    document.body.appendChild(notification);
    setTimeout(function() {
      return notification.classList.add('show');
    }, 10);
    return setTimeout(function() {
      notification.classList.remove('show');
      return setTimeout(function() {
        return notification.remove();
      }, 300);
    }, 3000);
  };

  // Handle form submission status messages
  handleFormStatus = function() {
    var formContainer, message, messageDiv, status, urlParams;
    urlParams = new URLSearchParams(window.location.search);
    status = urlParams.get('status');
    message = urlParams.get('message');
    if (status && message) {
      formContainer = document.querySelector('.form-container');
      if (formContainer) {
        messageDiv = document.createElement('div');
        messageDiv.className = `form-message ${status}`;
        messageDiv.textContent = decodeURIComponent(message);
        // Insert at the top of the form container
        formContainer.insertBefore(messageDiv, formContainer.firstChild);
        // Auto-remove success messages after 5 seconds
        if (status === 'success') {
          setTimeout(function() {
            return messageDiv.remove();
          }, 5000);
        }
        // Clear URL parameters
        return window.history.replaceState({}, document.title, window.location.pathname);
      }
    }
  };

  // Mobile menu toggle
  document.addEventListener('DOMContentLoaded', function() {
    var links, menu, toggle;
    toggle = document.querySelector('.nav-toggle');
    menu = document.querySelector('.nav-menu');
    if (toggle && menu) {
      toggle.addEventListener('click', function() {
        return menu.classList.toggle('open');
      });
      // Close menu when a link is clicked
      links = menu.querySelectorAll('.nav-link');
      links.forEach(function(link) {
        return link.addEventListener('click', function() {
          return menu.classList.remove('open');
        });
      });
    }
    // Initialize stats on page load
    initializeStats();
    // Handle form status messages
    return handleFormStatus();
  });

  document.getElementById;

}).call(this);
